### ISSUE TITLE
[依頼]ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Mizuki-Niiyama** [MN0607/protospace-35359#1]
# URL
https://protospace-35359.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるようにしましょう**
「さん」が抜けていたので修正しましょう。

- [ ] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できるようにしましょう**
ログアウトの状態のときに遷移できません。

- [ ] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるようにしましょう**
トップページ・プロトタイプ詳細ページ・ユーザー詳細ページに遷移できません。（ログインページに遷移してしまいます。）

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Mizuki-Niiyama** [comment]
ご確認ありがとうございます！

上記の点、全て修正が完了したと思いますので、再度ご確認お願いいたします。
よろしくお願いいたします。

**Comment by takumi0530** [comment]
@MN0607 さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
